<template>
  <div v-if="show" class="modal fade show" tabindex="-1" style="display: block; background-color: rgba(0,0,0,0.5);" @click.self="handleBackdropClick">
    <div class="modal-dialog modal-dialog-centered modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">使用须知 / Terms of Use</h5>
        </div>
        <div class="modal-body">
          <h6>中文说明</h6>
          <p>
            PRTS 是根据 GNU GPL v3 许可证发布的自由软件。当您使用本软件生成轨迹数据并公开使用、展示或分发这些内容时，我们建议您注明该内容是使用 PRTS 生成的。
          </p>
          <p>
            此建议不限制 GPLv3 授予您修改、分发或使用软件本身的权利。
          </p>
          <hr />
          <h6>English Notice</h6>
          <p>
            <strong>Additional Permission under GNU GPL version 3 section 7:</strong>
          </p>
          <p>
            When you publicly use, display, or distribute works generated by this software, you are encouraged to provide a notice stating that the work was generated using PRTS. This requirement does not restrict your rights granted by the GPLv3 to modify, distribute, or use the software itself.
          </p>
          <div class="form-check mt-3">
            <input class="form-check-input" type="checkbox" v-model="agreed" id="agreeCheck">
            <label class="form-check-label" for="agreeCheck">
              我已阅读并理解上述说明 / I have read and understood the above notice
            </label>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" :disabled="!agreed" @click="handleAgree">
            确认 / Confirm
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

defineProps<{
  show: boolean
}>()

const emit = defineEmits<{
  agree: []
}>()

const agreed = ref(false)

function handleAgree() {
  if (agreed.value) {
    emit('agree')
  }
}

function handleBackdropClick() {
  // Prevent closing modal by clicking backdrop
  // User must click the agree button
}
</script>

<style scoped>
.modal.show {
  pointer-events: auto;
}

.modal-body h6 {
  font-weight: 600;
  margin-top: 0.5rem;
  margin-bottom: 0.75rem;
}

.modal-body p {
  margin-bottom: 0.5rem;
}
</style>
