<template>
  <div v-if="show" class="modal fade show" tabindex="-1" style="display: block; background-color: rgba(0,0,0,0.5);" @click.self="handleBackdropClick">
    <div class="modal-dialog modal-dialog-centered modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">使用须知 / Terms of Use</h5>
        </div>
        <div class="modal-body">
          <h6>中文说明</h6>
          <p>
            <strong>GPLv3 第7条附加条款 - 衍生数据结构的署名要求</strong>
          </p>
          <p>
            本程序生成包含特定数据结构的文件（包括但不限于 JSON 格式），这些数据结构由版权持有人原创设计。
          </p>
          <p>
            如果您分发、发布或使用任何此类结构化数据，或从中衍生的作品（包括对相同架构或格式的重新实现或改编），您必须包含一个可见的声明，说明：
          </p>
          <p class="notice-text">
            "本作品（或其部分）包含由 PRTS 生成的数据结构，遵循 GPLv3 许可证。"
          </p>
          <p>
            此署名要求仅适用于包含或衍生自本程序受版权保护的数据结构或资源的作品，不限制使用本程序生成独立的、非衍生数据。
          </p>
          <hr />
          <h6>English Notice</h6>
          <p>
            <strong>Additional Terms under GNU GPL v3 Section 7 - Attribution Requirement for Derived Data Structures</strong>
          </p>
          <p>
            This program generates structured data files (including but not limited to JSON) that encode original data schemas and formats designed by the copyright holder.
          </p>
          <p>
            If you distribute, publish, or incorporate any such structured data, or any work derived from it (including reimplementations or adaptations of the same schema or format), you must include a visible notice stating:
          </p>
          <p class="notice-text">
            "This work (or portions thereof) incorporates data structures originally generated by PRTS, licensed under GPLv3."
          </p>
          <p>
            This attribution requirement applies only to works containing or derived from the program's copyrighted data structures or resources, and does not restrict the use of the program to produce independent, non-derivative data.
          </p>
          <div class="form-check mt-3">
            <input class="form-check-input" type="checkbox" v-model="agreed" id="agreeCheck">
            <label class="form-check-label" for="agreeCheck">
              我已阅读并理解上述说明 / I have read and understood the above notice
            </label>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" :disabled="!agreed" @click="handleAgree">
            确认 / Confirm
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

defineProps<{
  show: boolean
}>()

const emit = defineEmits<{
  agree: []
}>()

const agreed = ref(false)

function handleAgree() {
  if (agreed.value) {
    emit('agree')
  }
}

function handleBackdropClick() {
  // Prevent closing modal by clicking backdrop
  // User must click the agree button
}
</script>

<style scoped>
.modal.show {
  pointer-events: auto;
}

.modal-body h6 {
  font-weight: 600;
  margin-top: 0.5rem;
  margin-bottom: 0.75rem;
}

.modal-body p {
  margin-bottom: 0.5rem;
}

.notice-text {
  background-color: #f8f9fa;
  border-left: 3px solid #0d6efd;
  padding: 0.75rem;
  margin: 0.75rem 0;
  font-style: italic;
}
</style>
